### ISSUE TITLE
Why no support for NETStandard?

### ISSUE THREAD

**Issue by stefandevo** [Cloudmersive/Cloudmersive.APIClient.NETCore.VirusScan#1]
There is no reason to limit the assembly to NETCoreApp

https://github.com/Cloudmersive/Cloudmersive.APIClient.NETCore.VirusScan/blob/master/client/src/Cloudmersive.APIClient.NETCore.VirusScan/Cloudmersive.APIClient.NETCore.VirusScan.csproj#L4

This prevents to reference the library from another assembly where all other services are defined.

**Comment by Cloudmersive** [comment]
Thanks for sharing this.  This issue has been resolved with the new 2.0.2 version release.
